### ISSUE TITLE
Discord server invite link invalid in README

### ISSUE THREAD

**Issue by abdalaosama** [haythamhakim/projectpalestine#2]
The Contribution Invite Link is Invalid, Please update.

![image](https://github.com/haythamhakim/projectpalestine/assets/31589975/a6ffb75e-3b3c-4c46-9e9e-2e32d2e2afba)

**Comment by haythamhakim** [comment]
Thanks for pointing this out

**Comment by abdalaosama** [comment]
Hey, I think this isn't resolved yet. the problem was with the "stage 2: mobile app" discord invite link.
please check #7
