### ISSUE TITLE
[Google Form ] Invalid Discord link

### ISSUE THREAD

**Issue by moHaHa** [haythamhakim/projectpalestine#3]
https://docs.google.com/forms/d/e/1FAIpQLSc45_ExeU_TYmXGathFTYDlgHOg_LXxe4CLA9m47p7qV0LUEQ/viewform

![image](https://github.com/haythamhakim/projectpalestine/assets/72744132/33a0709e-a691-4bc8-8e67-6ff7e011caad)

**Comment by haythamhakim** [comment]
Add the correct link
