### ISSUE TITLE
[403] : Firebase  

### ISSUE THREAD

**Issue by moHaHa** [haythamhakim/projectpalestine#9]
I live in syria , we kind of blocked from many online services , any way here when I open the website , I can't see any result , so I checked network I got this 

I Don't know if this the reason or not, I know I can't use firebase as devoloper , but also as user !!

![image](https://github.com/haythamhakim/projectpalestine/assets/72744132/5e4b3e67-75f4-471b-b6f6-9019ad2b308a)

env : https://www.projectpalestine.org/

**Comment by moHaHa** [comment]
why we don't use  Our Backend ?! 
I mean not only for this bug ,  but for the whole project, is it better ? or firebase can give us all we want?

**Comment by haythamhakim** [comment]
We can create our backend. Would you like to work on that? I messaged you on discord. Will close this :)

**Comment by moHaHa** [comment]
@haythamhakim  
> Would you like to work on that? 

Hmm sure, why not 

I don't have much time but I will try 
for that, 
1. I need UML class diagram(s) and their relationships.
2. I have experience with Laravel, not that good ...but I can't implement all the features we need
